#!/bin/sh

# huawei cloud functiongraph
export PATH="/opt/function/runtime/nodejs14.18/rtsp/nodejs/bin/:$PATH"

if [ -z $RUNTIME_CODE_ROOT ]; then
  RUNTIME_CODE_ROOT=$PWD
fi

NODE_ENV=production node $RUNTIME_CODE_ROOT/server/server.js